# This file is generated by gyp; do not edit.

export builddir_name ?= /home/vishal.thanki/projects/git/src/src/client/windows/unittests/out
.PHONY: all
all:
	$(MAKE) -C ../../.. processor_bits client_tests
